name: Build Windows GUI EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          update: true

      - name: Build EXE
        run: |
          mkdir build
          gcc C/dummy.c -o build/dummy.exe -mwindows

      - uses: actions/upload-artifact@v4
        with:
          name: dummy-gui-exe
          path: build/dummy.exe
